# Generated by Django 4.2.6 on 2025-02-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
